### ISSUE TITLE
Docx comments in html

### ISSUE THREAD

**Issue by dbaynard** [jgm/pandoc-templates#213]
With jgm/pandoc@8bb739f documents converted from `docx` format with `--track-changes=all` will produce `span class="comment-start"` and `span class="comment-end"` blocks.

These are then displayed in html and html5 output inline in the text (i.e. not as comments) unless handled in CSS. It would be good to handle these for files which do not use an external css file.

Perhaps use the `no-select` family of options to avoid accidental copy-paste, and something like
```css
span.comment-start {
    position: relative;
    float: right;
    border: black solid thin;
    background-color: bisque;
    padding: 6px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
}
span.comment-start:after {
    content: "--" attr(author);
    display: block;
    text-align: right;
}
span.comment-start:before {
    content: "(" attr(date) ")";
    display: block;
    text-align: right;
}
```

This would then be added directly into the html template, above the css inclusion part (meaning it would be overwritten by any included css files).

**Comment by dbaynard** [comment]
Better (as it leaves the `::before` free, so plays nicely with, among other things, prince’s `float: footnote`)

```css
span.comment-start
{
  position            : relative;
  float               : right;
  border              : solid 1px black;
  background-color    : bisque;
  padding             : 6px 6px 6px 6px;
  -webkit-user-select : none;
  -moz-user-select    : none;
  -ms-user-select     : none;
  -o-user-select      : none;
  user-select         : none;
  font-size           : initial;
  font-weight         : initial;
  font-family         : initial;
  font-style          : initial;
}

span.comment-start::after
{
  content     : "— " attr(author) "\a(" attr(date) ")";
  display     : block;
  white-space : pre-wrap;
  text-align  : right;
}
```
